### ISSUE TITLE
How to build OpenH264DotNet.Native?

### ISSUE THREAD

**Issue by lwdddddddd** [takuya-takeuchi/OpenH264DotNet#2]
It reported an  error when i build OpenH264DotNet.Native using cmake.
-------------------------------------------------------
-- CMAKE_SYSTEM_INFO_FILE: Platform/Windows
-- CMAKE_SYSTEM_NAME:      Windows
-- CMAKE_SYSTEM_PROCESSOR: AMD64
-- CMAKE_SYSTEM:           Windows-10.0.18363
-- CMAKE_C_COMPILER:       C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
-- CMAKE_CXX_COMPILER:     C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
-- os_version_suffix:      
-- Project: E:/vvwork/VS-project/OpenH264DotNet-main/src/OpenH264DotNet.Native
-- Binaries: E:/vvwork/VS-project/OpenH264DotNet-main/src/OpenH264DotNet.Native/build
-------------------------------------------------------
-- CMAKE_BUILD_TYPE: Release
CMake Error at CMakeLists.txt:104 (include_directories):
  include_directories given empty-string as include directory.

**Comment by takuya-takeuchi** [comment]
@lwdddddddd 
You can use https://github.com/takuya-takeuchi/OpenH264DotNet/blob/main/nuget/BuildWindows.ps1.

````bat
pwsh BuildWindows.ps1
````

You must install PowerShell Core rather than PowerShell.
